name: DyrtCraftSG
version: Beta 1.0.0
website: http://dyrtcraft.pl/
author: TheMolkaPL
description: Plugin stworzony specjalnie dla DyrtCraft Network!

main: pl.DyrtCraft.SurvivalGames.DyrtCraftSG

commands:
    dcsg:
        description: Komendy administracyjne DyrtCraftSG
        usage: /dcsg <info|reload|setlobby>
    lobby:
        description: Teleportacja do Lobby
        usage: /lobby [Gracz]
    ?:
        description: Pomoc
        aliases: [help, ehelp]
        usage: /?
# Copyright © 2013 DyrtCraft Network All rights reserved.